trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install Dependencies'

- script: npm run build-storybook
  displayName: 'Build the Storybook App'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/storybook-static' #path to build folder
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'

# Add tasks to deploy the artifacts to your hosting platform (e.g., Azure App Service, Azure Static Web Apps, etc.)
# Refer to the documentation of your hosting platform for specific deployment steps.
